databases:
  - name: sistema_poa_db
    databaseName: sistema_poa
    user: sistema_poa_user

services:
  - type: web
    name: sistema_poa
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn alcaldiaPOA.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sistema_poa_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
