# Generated by Django 4.2.11 on 2025-10-09 04:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Actividad')),
                ('unidad_medida', models.CharField(max_length=80, verbose_name='Unidad de Medida')),
                ('cantidad_programada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Programada')),
                ('es_cuantificable', models.BooleanField(default=True, verbose_name='Es Cuantificable')),
                ('medio_verificacion', models.TextField(blank=True, verbose_name='Medio de Verificación')),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos')),
                ('total_recursos', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Recursos (Bs.)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['meta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre del Proyecto')),
                ('objetivo_unidad', models.TextField(blank=True, verbose_name='Objetivo de la Unidad')),
                ('anio', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Año')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('unidad', models.ForeignKey(limit_choices_to={'rol': 'UNIDAD'}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to=settings.AUTH_USER_MODEL, verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-anio', 'unidad__unidad__nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Meta')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='poa.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['proyecto', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('FOTO', 'Foto'), ('VIDEO', 'Video'), ('URL', 'URL'), ('MP3', 'Audio MP3')], max_length=10, verbose_name='Tipo')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/', verbose_name='Archivo')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('mes', models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True, verbose_name='Mes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='poa.actividad', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('tabla', models.CharField(max_length=50, verbose_name='Tabla')),
                ('registro_id', models.IntegerField(verbose_name='ID del Registro')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='poa.metaproyecto', verbose_name='Meta'),
        ),
        migrations.CreateModel(
            name='AvanceMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('anio', models.IntegerField(default=2025, verbose_name='Año')),
                ('cantidad_programada_mes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Programada')),
                ('cantidad_realizada', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Realizada')),
                ('cumplimiento', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Cumplimiento %')),
                ('causal_incumplimiento', models.TextField(blank=True, verbose_name='Causal de Incumplimiento')),
                ('es_no_planificada', models.BooleanField(default=False, verbose_name='Es No Planificada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='poa.actividad', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Avance Mensual',
                'verbose_name_plural': 'Avances Mensuales',
                'ordering': ['actividad', 'anio', 'mes'],
                'unique_together': {('actividad', 'mes', 'anio')},
            },
        ),
    ]
