# Generated by Django 4.2.11 on 2025-10-09 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='cantidad_programada',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Cantidad Programada'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='total_recursos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999.99)], verbose_name='Total Recursos (Bs.)'),
        ),
        migrations.AlterField(
            model_name='avancemensual',
            name='anio',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='avancemensual',
            name='cantidad_programada_mes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Cantidad Programada'),
        ),
        migrations.AlterField(
            model_name='avancemensual',
            name='cantidad_realizada',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Cantidad Realizada'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='anio',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año'),
        ),
    ]
