# Generated by Django 4.2.11 on 2025-10-11 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poa', '0002_alter_actividad_cantidad_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
