# Generated by Django 5.2.7 on 2025-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0003_proyecto_aprobado_por_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
    ]
