# Generated by Django 5.2.7 on 2025-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0004_proyecto_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción de la Actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='medio_verificacion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Medio de Verificación'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='recursos',
            field=models.CharField(blank=True, max_length=500, verbose_name='Recursos'),
        ),
        migrations.AlterField(
            model_name='avancemensual',
            name='causal_incumplimiento',
            field=models.CharField(blank=True, max_length=500, verbose_name='Causal de Incumplimiento'),
        ),
        migrations.AlterField(
            model_name='metaproyecto',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción de la Meta'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Motivo de Rechazo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='objetivo_unidad',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Objetivo de la Unidad'),
        ),
    ]
