# Generated by Django 5.2.7 on 2025-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0005_alter_actividad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaproyecto',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción de la Meta'),
        ),
    ]
