# Generated by Django 5.2.7 on 2025-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0006_alter_metaproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancemensual',
            name='cumplimiento',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Cumplimiento %'),
        ),
    ]
