# Generated by Django 5.2.7 on 2025-11-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0007_alter_avancemensual_cumplimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proyecto'),
        ),
    ]
