# Generated by Django 5.2.7 on 2025-11-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0008_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='medio_verificacion',
            field=models.CharField(max_length=500, verbose_name='Medio de Verificación'),
        ),
    ]
