# Generated by Django 5.2.7 on 2025-11-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0009_alter_actividad_medio_verificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPredeterminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Meta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta Predeterminada',
                'verbose_name_plural': 'Metas Predeterminadas',
                'ordering': ['nombre'],
            },
        ),
    ]
