# Generated by Django 5.2.7 on 2025-11-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0011_objetivoestrategico'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='es_no_planificado',
            field=models.BooleanField(default=False, verbose_name='Es Proyecto No Planificado'),
        ),
    ]
